<a href="https://colab.research.google.com/github/mnaredla-cloud/GenAI/blob/main/8)Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
##### Feature_Extraction #####


In [14]:
from transformers import pipeline
feature_extraction=pipeline(task="feature-extraction")
text = "Citi bank is one of the popular bank in USA"
results = feature_extraction(text)
print(results)

No model was supplied, defaulted to distilbert/distilbert-base-cased and revision 6ea8117 (https://huggingface.co/distilbert/distilbert-base-cased).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[[[0.3910025656223297, 0.05040422081947327, -0.40429452061653137, -0.17863523960113525, -0.39250612258911133, -0.09721840918064117, 0.11720330268144608, 0.15248335897922516, -0.1290910243988037, -0.9218080639839172, -0.3276892602443695, 0.03229733929038048, -0.29364341497421265, 0.015363997779786587, -0.26520290970802307, -0.13844570517539978, 0.02475312352180481, 0.014157276600599289, -0.06681584566831589, -0.06942406296730042, -0.05589096620678902, -0.18028278648853302, 0.48331373929977417, -0.2143317013978958, 0.2337716817855835, -0.005892743822187185, 0.25031736493110657, 0.5213611721992493, -0.23353511095046997, 0.2163509577512741, -0.20903140306472778, 0.34689417481422424, -0.0890471562743187, 0.05591648072004318, -0.2118804156780243, 0.17325034737586975, 0.17700377106666565, -0.3259921073913574, -0.08016809076070786, -0.08177732676267624, -0.3821640908718109, 0.0015510760713368654, 0.5973086357116699, 0.1320672184228897, 0.07329612970352173, -0.4955002963542938, -0.0429485403001

In [15]:
from transformers import pipeline
feature_extraction = pipeline(task="feature-extraction")
text = "Citi bank is one of the popular bank in USA"
result = feature_extraction(text, return_tensors="pt")
print(result)
print(result.shape)

No model was supplied, defaulted to distilbert/distilbert-base-cased and revision 6ea8117 (https://huggingface.co/distilbert/distilbert-base-cased).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


tensor([[[ 0.3910,  0.0504, -0.4043,  ..., -0.1042,  0.1959,  0.0997],
         [-0.2258, -0.0117, -0.2337,  ...,  0.5411,  0.1668,  0.0374],
         [-0.2238,  0.0757,  0.0425,  ...,  0.3956, -0.2177,  0.4193],
         ...,
         [-0.0881, -0.2393, -0.2992,  ...,  0.2839,  0.0722, -0.0747],
         [-0.2363, -0.1031, -0.2278,  ...,  0.0257,  0.3337,  0.1475],
         [ 0.0072, -0.2174, -0.9647,  ...,  0.3218,  0.9029,  0.1357]]])
torch.Size([1, 13, 768])


In [16]:
##### Extracting_Static_Embeddinds  #####

# return_tensors = "pt" >> for holding tensor >> pt =pytorch

from transformers import pipeline

text = "Citi bank is one of the popular bank in USA"

feature_excecutor = pipeline("feature-extraction")

results= feature_excecutor(text, return_tensors = "pt")

print(results)

No model was supplied, defaulted to distilbert/distilbert-base-cased and revision 6ea8117 (https://huggingface.co/distilbert/distilbert-base-cased).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


tensor([[[ 0.3910,  0.0504, -0.4043,  ..., -0.1042,  0.1959,  0.0997],
         [-0.2258, -0.0117, -0.2337,  ...,  0.5411,  0.1668,  0.0374],
         [-0.2238,  0.0757,  0.0425,  ...,  0.3956, -0.2177,  0.4193],
         ...,
         [-0.0881, -0.2393, -0.2992,  ...,  0.2839,  0.0722, -0.0747],
         [-0.2363, -0.1031, -0.2278,  ...,  0.0257,  0.3337,  0.1475],
         [ 0.0072, -0.2174, -0.9647,  ...,  0.3218,  0.9029,  0.1357]]])


In [17]:
# Extracting_Static_Embeddinds

# return_tensors = "pt" >> for holding tensor >> pt =pytorch

# print(results.shape) >> for printing no:of tokens (dimensions)

from transformers import pipeline

text = "Citi bank is one of the popular bank in USA"

feature_excecutor = pipeline("feature-extraction")

results= feature_excecutor(text, return_tensors = "pt")

print(results)

print(results.shape)

No model was supplied, defaulted to distilbert/distilbert-base-cased and revision 6ea8117 (https://huggingface.co/distilbert/distilbert-base-cased).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


tensor([[[ 0.3910,  0.0504, -0.4043,  ..., -0.1042,  0.1959,  0.0997],
         [-0.2258, -0.0117, -0.2337,  ...,  0.5411,  0.1668,  0.0374],
         [-0.2238,  0.0757,  0.0425,  ...,  0.3956, -0.2177,  0.4193],
         ...,
         [-0.0881, -0.2393, -0.2992,  ...,  0.2839,  0.0722, -0.0747],
         [-0.2363, -0.1031, -0.2278,  ...,  0.0257,  0.3337,  0.1475],
         [ 0.0072, -0.2174, -0.9647,  ...,  0.3218,  0.9029,  0.1357]]])
torch.Size([1, 13, 768])


In [18]:
#Extracting static embeddings >>Passing model

#using facebook/bart-base

from transformers import pipeline

text = "Citi bank is one of the popular bank in USA"

feature_excecutor = pipeline("feature-extraction", model = "facebook/bart-base")

results= feature_excecutor(text, return_tensors = "pt")

print(results)

print(results.shape)

Device set to use cpu


tensor([[[ 2.6692,  2.6544,  1.1080,  ...,  1.6719,  0.0237, -0.8007],
         [-1.0192,  0.0513, -2.1891,  ...,  1.5820, -1.4139,  0.1209],
         [-1.6490,  0.8207, -3.9101,  ..., -1.6382,  0.9687,  0.0318],
         ...,
         [-1.7075,  0.9629, -4.7106,  ...,  1.7070, -2.5677,  0.4708],
         [-0.4541, -0.1377, -1.6489,  ...,  0.8247, -0.9324, -0.4853],
         [-1.0132, -0.4923,  0.4780,  ...,  0.8772, -2.1775,  0.4083]]])
torch.Size([1, 13, 768])
