<a href="https://colab.research.google.com/github/mnaredla-cloud/GenAI/blob/main/make_more.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#For uploading file.
#import files library from google.colab
#use upload() function for uploading file

from google.colab import files
uploaded = files.upload()

Saving indian_names.txt to indian_names (1).txt


In [29]:
#open the uploaded file and read the file and split the lines

names = open('indian_names.txt','r').read().splitlines()

In [33]:
# Print sample 10 names

print(names[0:10])

['Vihaan', 'Aarav', 'Ishaan', 'Vihaan', 'Anaya', 'Sai', 'Anika', 'Avni', 'Sai', 'Vihaan']


In [37]:
#Total no:of names

len(names)

1000

In [38]:
#DataType of names

type(names)

list

In [41]:
#Get the minimum length of name outof supplied 1000 names

min(len(name) for name in names)

3

In [42]:
#Get the maximum length of name outof supplied 1000 names

max(len(name) for name in names)

7

In [43]:
#For each name, convert string to list and add <S> at start and <E> at the end.
#output>> ['<S>', 'V', 'i', 'h', 'a', 'a', 'n', '<E>']
for name in names:
  chr = ['<S>'] + list(name) + ['<E>']
  print(chr)

['<S>', 'V', 'i', 'h', 'a', 'a', 'n', '<E>']
['<S>', 'A', 'a', 'r', 'a', 'v', '<E>']
['<S>', 'I', 's', 'h', 'a', 'a', 'n', '<E>']
['<S>', 'V', 'i', 'h', 'a', 'a', 'n', '<E>']
['<S>', 'A', 'n', 'a', 'y', 'a', '<E>']
['<S>', 'S', 'a', 'i', '<E>']
['<S>', 'A', 'n', 'i', 'k', 'a', '<E>']
['<S>', 'A', 'v', 'n', 'i', '<E>']
['<S>', 'S', 'a', 'i', '<E>']
['<S>', 'V', 'i', 'h', 'a', 'a', 'n', '<E>']
['<S>', 'S', 'a', 'i', '<E>']
['<S>', 'V', 'i', 'v', 'a', 'a', 'n', '<E>']
['<S>', 'A', 'd', 'i', 't', 'y', 'a', '<E>']
['<S>', 'A', 'a', 'd', 'h', 'y', 'a', '<E>']
['<S>', 'K', 'r', 'i', 's', 'h', 'n', 'a', '<E>']
['<S>', 'D', 'i', 'y', 'a', '<E>']
['<S>', 'I', 's', 'h', 'a', 'a', 'n', '<E>']
['<S>', 'D', 'i', 'y', 'a', '<E>']
['<S>', 'K', 'r', 'i', 's', 'h', 'n', 'a', '<E>']
['<S>', 'M', 'e', 'e', 'r', 'a', '<E>']
['<S>', 'A', 'r', 'y', 'a', 'n', '<E>']
['<S>', 'A', 'a', 'd', 'h', 'y', 'a', '<E>']
['<S>', 'A', 'r', 'j', 'u', 'n', '<E>']
['<S>', 'A', 'r', 'y', 'a', 'n', '<E>']
['<S>', 'A', 'a', 'd

In [44]:
#For each name, convert string to list and add <S> at start and <E> at the end.
# chr= ['<S>', 'V', 'i', 'h', 'a', 'a', 'n', '<E>']

#for ch1,ch2 in zip(chr,chr[1:]):
#take input of chr and input of chr by neglecting 1st charector

for name in names:
  chr = ['<S>'] + list(name) + ['<E>']
  for ch1,ch2 in zip(chr,chr[1:]):
    print(ch1,ch2)

<S> V
V i
i h
h a
a a
a n
n <E>
<S> A
A a
a r
r a
a v
v <E>
<S> I
I s
s h
h a
a a
a n
n <E>
<S> V
V i
i h
h a
a a
a n
n <E>
<S> A
A n
n a
a y
y a
a <E>
<S> S
S a
a i
i <E>
<S> A
A n
n i
i k
k a
a <E>
<S> A
A v
v n
n i
i <E>
<S> S
S a
a i
i <E>
<S> V
V i
i h
h a
a a
a n
n <E>
<S> S
S a
a i
i <E>
<S> V
V i
i v
v a
a a
a n
n <E>
<S> A
A d
d i
i t
t y
y a
a <E>
<S> A
A a
a d
d h
h y
y a
a <E>
<S> K
K r
r i
i s
s h
h n
n a
a <E>
<S> D
D i
i y
y a
a <E>
<S> I
I s
s h
h a
a a
a n
n <E>
<S> D
D i
i y
y a
a <E>
<S> K
K r
r i
i s
s h
h n
n a
a <E>
<S> M
M e
e e
e r
r a
a <E>
<S> A
A r
r y
y a
a n
n <E>
<S> A
A a
a d
d h
h y
y a
a <E>
<S> A
A r
r j
j u
u n
n <E>
<S> A
A r
r y
y a
a n
n <E>
<S> A
A a
a d
d h
h y
y a
a <E>
<S> V
V i
i h
h a
a a
a n
n <E>
<S> D
D i
i y
y a
a <E>
<S> D
D i
i y
y a
a <E>
<S> A
A r
r j
j u
u n
n <E>
<S> A
A r
r j
j u
u n
n <E>
<S> M
M e
e e
e r
r a
a <E>
<S> D
D h
h r
r u
u v
v <E>
<S> S
S a
a a
a n
n v
v i
i <E>
<S> I
I s
s h
h a
a a
a n
n <E>
<S> S
S a
a i
i <E>
<S> 

In [60]:
#define a empty dictonary >>b
#tuple of ch1,ch2   >>('<S>', 'V')

b = {}
for name in names[0:1]:
  chr = ['<S>'] + list(name) + ['<E>']
  for ch1,ch2 in zip(chr,chr[1:]):
    biagram = (ch1,ch2)
    b[biagram] = b.get(biagram,0) + 1

In [59]:
# Print output of dictonary for 1 input

print(b)

{('<S>', 'V'): 1, ('V', 'i'): 1, ('i', 'h'): 1, ('h', 'a'): 1, ('a', 'a'): 1, ('a', 'n'): 1, ('n', '<E>'): 1}


In [61]:
#for importing torch library

import torch

In [62]:
#Create a Tensor of 3x5 with zeros
#by default floating value

N = torch.zeros(3,5)
print(N)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [63]:
# To check the size of tensor

N.shape

torch.Size([3, 5])

In [64]:
#conver float to int(32)

N = torch.zeros((3,5), dtype = torch.int32)
print(N)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [66]:
#update tensor value

N[1,3] = 5
print(N)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 5, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [68]:
#get first 5 names

names[0:5]

['Vihaan', 'Aarav', 'Ishaan', 'Vihaan', 'Anaya']

In [69]:
#join first 5 names

''.join(names[0:5])

'VihaanAaravIshaanVihaanAnaya'

In [66]:
#join first 5 names with spaces

' '.join(names[0:5])

'Vihaan Aarav Ishaan Vihaan Anaya'

In [72]:
#set,keeps only unique values.....drops duplicates

set(''.join(names[0:5]))

{'A', 'I', 'V', 'a', 'h', 'i', 'n', 'r', 's', 'v', 'y'}

In [77]:
#values in sorted order

sorted(set(''.join(names[0:5])))

['A', 'I', 'V', 'a', 'h', 'i', 'n', 'r', 's', 'v', 'y']

In [78]:
#Create a 28x28 2d-tensor

T = torch.zeros((28,28), dtype = torch.int32)

In [79]:
print(T)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [80]:
#print unique charectors

chars = sorted(list(set(''.join(names))))
print(chars)

['A', 'D', 'I', 'K', 'M', 'R', 'S', 'V', 'a', 'd', 'e', 'h', 'i', 'j', 'k', 'n', 'r', 's', 't', 'u', 'v', 'y']


In [83]:
#For printing index, value of the unique charectors

for i,s in enumerate(chars):
  print(i,s)

A 0
D 1
I 2
K 3
M 4
R 5
S 6
V 7
a 8
d 9
e 10
h 11
i 12
j 13
k 14
n 15
r 16
s 17
t 18
u 19
v 20
y 21


In [96]:
#interchange index,value with value,index
#and dtype to dict with values:key

stoi = {s:i for i,s in enumerate(chars)}

In [98]:
#add two more vales with it's index values at 26,27

stoi['<S>'] = 26
stoi['<E>'] = 27

In [99]:
print(stoi)

{'A': 0, 'D': 1, 'I': 2, 'K': 3, 'M': 4, 'R': 5, 'S': 6, 'V': 7, 'a': 8, 'd': 9, 'e': 10, 'h': 11, 'i': 12, 'j': 13, 'k': 14, 'n': 15, 'r': 16, 's': 17, 't': 18, 'u': 19, 'v': 20, 'y': 21, '<S>': 26, '<E>': 27}


In [102]:
#index_1 =index[ch1]
#index_2 =index[ch2]
#T[index_1,index_2] = T[index_1,index_2] + 1
#T-Tensor

for W in names:
  chr = ['<S>'] + list(W) + ['<E>']
  for ch1,ch2 in zip(chr,chr[1:]):
    index_1 = stoi[ch1]
    index_2 = stoi[ch2]
    T[index_1,index_2] += 1

In [103]:
print(T)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 192,  88,   0,   0,   0,   0,
           0, 226, 222,   0,   0,   0, 104,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  92, 102,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  96,  94,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 102,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  92,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,  64,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 120,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [115]:
stoi = {s:i for i,s in enumerate(chars)}

In [121]:
#value,index

print(stoi)

{'A': 0, 'D': 1, 'I': 2, 'K': 3, 'M': 4, 'R': 5, 'S': 6, 'V': 7, 'a': 8, 'd': 9, 'e': 10, 'h': 11, 'i': 12, 'j': 13, 'k': 14, 'n': 15, 'r': 16, 's': 17, 't': 18, 'u': 19, 'v': 20, 'y': 21}


In [122]:
itos = {i:s for s,i in stoi.items()}

In [123]:
#index,value

print(itos)

{0: 'A', 1: 'D', 2: 'I', 3: 'K', 4: 'M', 5: 'R', 6: 'S', 7: 'V', 8: 'a', 9: 'd', 10: 'e', 11: 'h', 12: 'i', 13: 'j', 14: 'k', 15: 'n', 16: 'r', 17: 's', 18: 't', 19: 'u', 20: 'v', 21: 'y'}


In [ ]:
import matplotlib.pyplot as plt
